# Generated by Django 3.2 on 2021-12-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
