# Generated by Django 3.2 on 2021-12-08 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_item_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
