# Generated by Django 3.2 on 2021-12-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_item_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='created_on',
        ),
    ]
