# Generated by Django 3.2 on 2021-12-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_auto_20211208_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imdbLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
