# Generated by Django 3.2 on 2021-12-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_item_imdblink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imdbLink',
            new_name='imdb_link',
        ),
    ]
