# Generated by Django 3.2 on 2021-12-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_rename_imdblink_item_imdb_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imdb_link',
            field=models.URLField(default='https://www.imdb.com/title/tt0118715/'),
            preserve_default=False,
        ),
    ]
